include:
  - project: "devops/gitlab/ci-templates/docker"
    ref: "0.0.1"
    file:
      - ".build_docker_image.yml"
      - ".push_docker_image.yml"
      - ".remove_docker_image.yml"
      - ".remove_docker_image_from_registry.yml"
  - project: "devops/gitlab/ci-templates/ruby"
    ref: "sans-dind"
    file:
      - ".rspec.yml"
      - ".rubocop.yml"
  - project: "devops/gitlab/ci-templates/sast"
    ref: "master"
    file:
      - ".shiftleft_container_scanning.yml"
      - ".trivy_container_scanning.yml"
  - template: "Workflows/MergeRequest-Pipelines.gitlab-ci.yml"

stages:
  - .pre
  - push_tmp_image
  - test
  - sast
  - remove_tmp_image
  - push
  - .post

build_image:
  stage: .pre
  extends:
    - .build_docker_image
  tags:
    - build

push_tmp_image_to_registry:
  stage: push_tmp_image
  extends:
    - .push_docker_image
  needs:
    - build_image
  variables:
    IMAGE_TAGS: ${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}
  tags:
    - build

rspec_test:
  stage: test
  needs:
    - push_tmp_image_to_registry
  extends:
    - .rspec
  variables:
    RACK_ENV: "test"
  tags:
    - build

# **Work in Progress**
# rubocop:
#   stage: test
#   extends:
#     - .rubocop
#   variables:
#     RUBOCOP_DOCKER_ENV_VARS: "--env-file .env"
#   before_script:
#     - cp ${CI_PROJECT_DIR}/.env.example ${CI_PROJECT_DIR}/.env
#   tags:
#     - build

shiftleft_container_scanning:
  stage: sast
  extends:
    - .shiftleft_container_scanning
  needs:
    - push_tmp_image_to_registry
  tags:
    - build

trivy_container_scanning:
  stage: sast
  extends:
    - .trivy_container_scanning
  needs:
    - push_tmp_image_to_registry
  tags:
    - build
  allow_failure: true

delete_tmp_image_from_registry:
  stage: remove_tmp_image
  extends:
    - .remove_docker_image_from_registry
  rules:
    - when: always
  needs:
    - push_tmp_image_to_registry
    - rspec_test
    - shiftleft_container_scanning
    - trivy_container_scanning
  tags:
    - build
  allow_failure: true

push_image_to_registry:
  stage: push
  extends:
    - .push_docker_image
  needs:
    - delete_tmp_image_from_registry
    - shiftleft_container_scanning
    - trivy_container_scanning
    - rspec_test
  tags:
    - build

remove_image:
  stage: .post
  extends:
    - .remove_docker_image
  rules:
    - when: always
  needs:
    - build_image
    - push_image_to_registry
  tags:
    - build